"""
Household-level PolicyEngine simulation for the budget constraint figure.

Two execution modes:
  1. Pre-computed (fast, deployment-ready): load parquet schedules generated by
     WORKSPACE/code/01_data_preparation/01b_precompute_individual.py, then
     interpolate at runtime — no PolicyEngine calls needed.

  2. Live (development fallback): call PolicyEngine directly for every hour bin.
     Slow on first load (~1-3 min) but cached by Streamlit.

Public API
----------
run_from_precomputed(employer_wage, family_type, state_code, subsidy_params)
    → pd.DataFrame   (used by the app; auto-selects mode)

compute_income_point(annual_income, family_type, state_code)
    → dict           (used by the pre-computation pipeline)
"""
from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

# ── Hours axes ────────────────────────────────────────────────────────────────

# Continuous x-axis for the budget constraint figure
HOURS_CONTINUOUS: list[int] = list(range(0, 3121, 20))

# Reference bins used by the difference table
TABLE_HOURS: dict[int, str] = {
    0:    "0 hrs/wk",
    1040: "20 hrs/wk",
    2080: "40 hrs/wk",
    3120: "60 hrs/wk",
}

# ── Family types ──────────────────────────────────────────────────────────────

FAMILY_TYPES: dict[str, dict] = {
    "Single, 0 children":  {"adults": 1, "children": 0},
    "Single, 1 child":     {"adults": 1, "children": 1},
    "Single, 2 children":  {"adults": 1, "children": 2},
    "Single, 3 children":  {"adults": 1, "children": 3},
    "Married, 0 children": {"adults": 2, "children": 0},
    "Married, 1 child":    {"adults": 2, "children": 1},
    "Married, 2 children": {"adults": 2, "children": 2},
    "Married, 3 children": {"adults": 2, "children": 3},
}

# Short keys used in parquet filenames
FAMILY_KEYS: dict[str, str] = {
    "Single, 0 children":  "single_0c",
    "Single, 1 child":     "single_1c",
    "Single, 2 children":  "single_2c",
    "Single, 3 children":  "single_3c",
    "Married, 0 children": "married_0c",
    "Married, 1 child":    "married_1c",
    "Married, 2 children": "married_2c",
    "Married, 3 children": "married_3c",
}

YEAR_STR = "2026"

# ── Income components (display order + chart colors) ─────────────────────────

COMPONENTS = [
    # (key, label, color, is_positive)
    # Colors drawn from EIG brand palette (eig_tokens.py).
    # Primary / secondary brand colors used for main series.
    # Minor series (wic, school_meals, liheap, other_benefits) use
    # EIG-derived tints — acceptable brand extension for dense categoricals.
    # Tax bars use EIG red sequential scale (eig_seq_red_5).
    ("employer_wages",   "Employer wages",        "#194F8B", True),   # eig_blue_800
    ("wage_subsidy",     "Wage subsidy",          "#19644D", True),   # eig_green_700
    ("eitc",             "EITC",                 "#E1AD28", True),   # eig_gold_600
    ("child_tax_credit", "Child tax credit",     "#176F96", True),   # eig_cyan_700
    ("snap",             "SNAP",                 "#D6936F", True),   # eig_tan_500
    ("medicaid_chip",    "Medicaid / CHIP",      "#024140", True),   # eig_teal_900
    ("aca_ptc",          "ACA health subsidies", "#5E9C86", True),   # eig_green_500
    ("ssi",              "SSI",                  "#39274F", True),   # eig_purple_800
    ("tanf",             "TANF",                 "#F0B799", True),   # eig_tan_300
    ("housing",          "Section 8 / Housing",  "#B3D6DD", True),   # eig_blue_200
    ("ccdf",             "Child care (CCDF)",    "#A89F94", True),   # warm gray (brand guidelines)
    ("wic",              "WIC",                  "#8BBF9F", True),   # tint of eig_green_700
    ("school_meals",     "School meals",         "#8FA5BD", True),   # tint of eig_blue_800
    ("liheap",           "LIHEAP (energy)",      "#7B6B8A", True),   # tint of eig_purple_800
    ("other_benefits",   "Other benefits",       "#C5C0BB", True),   # warm neutral tint
    ("federal_tax",      "Federal income tax",   "#97310E", False),  # eig_seq_red_5[0]
    ("state_tax",        "State income tax",     "#D34917", False),  # eig_seq_red_5[1]
    ("payroll_tax",      "Payroll taxes",        "#F97D1E", False),  # eig_seq_red_5[2]
]

# Component keys that represent government-funded transfers
TRANSFER_KEYS = [
    "wage_subsidy", "eitc", "child_tax_credit",
    "snap", "medicaid_chip", "aca_ptc", "ssi", "tanf", "housing",
    "ccdf", "wic", "school_meals", "liheap", "other_benefits",
]

# Columns stored in each parquet schedule (analytic cols excluded)
_SCHEDULE_COLS = [
    "eitc", "child_tax_credit", "snap", "medicaid_chip", "aca_ptc",
    "ssi", "tanf", "housing", "ccdf", "wic", "school_meals", "liheap",
    "other_benefits", "federal_tax", "state_tax", "payroll_tax", "net_income",
]

# Path to pre-computed stylised schedules (built by 01b_precompute_individual.py)
_SCHEDULES_DIR: Path = (
    Path(__file__).resolve().parent  # utils/
    .parent                          # app/
    .parent                          # WORKSPACE/
    / "output" / "data" / "intermediate_results" / "individual_schedules"
)

# Path to matched-household schedules (built by 02d_precompute_matched_schedules.py)
_MATCHED_SCHEDULES_DIR: Path = (
    Path(__file__).resolve().parent
    .parent
    .parent
    / "output" / "data" / "intermediate_results" / "matched_schedules"
)

_SPOUSE_BUCKET_BOUNDS = [0, 1, 7_500, 12_500, 17_500, 22_500, 27_500, 37_500, 52_500, 72_500]
_SPOUSE_BUCKET_REPRS = [0, 5_000, 10_000, 15_000, 20_000, 25_000, 32_500, 45_000, 62_500, 87_500]


# ── PolicyEngine helpers ──────────────────────────────────────────────────────

def _build_situation(
    employment_income: float,
    family_type: str,
    state_code: str,
) -> dict:
    cfg = FAMILY_TYPES[family_type]
    n_adults = cfg["adults"]
    n_children = cfg["children"]

    people: dict = {}
    all_members: list[str] = []

    people["person1"] = {
        "age": {YEAR_STR: 35},
        "employment_income": {YEAR_STR: employment_income},
    }
    all_members.append("person1")

    if n_adults == 2:
        people["person2"] = {
            "age": {YEAR_STR: 33},
            "employment_income": {YEAR_STR: 0},
        }
        all_members.append("person2")

    child_ages = [8, 3, 6, 1]
    for i in range(n_children):
        cid = f"child{i + 1}"
        people[cid] = {
            "age": {YEAR_STR: child_ages[i]},
            "employment_income": {YEAR_STR: 0},
        }
        all_members.append(cid)

    adult_members = ["person1"] if n_adults == 1 else ["person1", "person2"]

    return {
        "people": people,
        "families": {"family1": {"members": all_members}},
        "marital_units": {"marital_unit1": {"members": adult_members}},
        "tax_units": {
            "tax_unit1": {
                "members": all_members,
                "tax_unit_is_joint": {YEAR_STR: n_adults == 2},
            }
        },
        "spm_units": {"spm_unit1": {"members": all_members}},
        "households": {
            "household1": {
                "members": all_members,
                "state_code": {YEAR_STR: state_code},
            }
        },
    }


def _get(sim, var: str) -> float:
    """Sum a PolicyEngine variable across all entity instances. Returns 0 on error."""
    try:
        return float(sim.calculate(var, YEAR_STR).sum())
    except Exception:
        return 0.0


def _try_vars(sim, *vars: str) -> float:
    """Try variable names in order; return the first non-zero result."""
    for var in vars:
        val = _get(sim, var)
        if val != 0.0:
            return val
    return 0.0


def _extract_components(sim, annual_income: float) -> dict:
    """
    Extract benefit/tax components from a PolicyEngine Simulation object.
    employer_wages and wage_subsidy are NOT included — those are analytic.
    """
    eitc    = max(0.0, _get(sim, "eitc"))
    ctc     = max(0.0, _try_vars(sim, "refundable_ctc", "child_tax_credit_refundable",
                                 "additional_child_tax_credit"))
    snap    = max(0.0, _get(sim, "snap"))

    # Medicaid / CHIP: imputed dollar value of coverage.
    # PolicyEngine-US computes per-enrollee costs from actuarial data.
    # We try several variable name patterns used across PE-US versions.
    medicaid_chip = max(0.0, _try_vars(
        sim,
        "medicaid_and_chip",
        "medicaid",
        "medicaid_benefit",
        "medicaid_and_chip_benefit",
    ))

    # ACA Premium Tax Credits (marketplace health insurance subsidies)
    aca_ptc = max(0.0, _try_vars(
        sim,
        "premium_tax_credit",
        "aca_premium_tax_credit",
        "ptc",
    ))

    ssi     = max(0.0, _get(sim, "ssi"))
    tanf    = max(0.0, _try_vars(sim, "tanf", "tanf_max_benefit"))

    # Section 8 / Housing Choice Vouchers and other housing assistance
    housing = max(0.0, _try_vars(
        sim,
        "housing_assistance",
        "section_8_housing_assistance",
        "housing_choice_voucher",
        "section_8",
    ))

    # Child care subsidies (CCDF)
    ccdf = max(0.0, _try_vars(
        sim,
        "ccdf_subsidy",
        "ccdf",
        "child_care_subsidy",
        "child_care_and_development_fund",
    ))

    # WIC (Women, Infants, and Children nutrition program)
    wic = max(0.0, _try_vars(
        sim,
        "wic",
        "wic_benefit",
    ))

    # Free / reduced-price school meals (NSLP)
    school_meals = max(0.0, _try_vars(
        sim,
        "school_meal_subsidy",
        "nslp",
        "free_school_meals",
        "school_lunch_subsidy",
        "free_and_reduced_price_school_meals",
    ))

    # LIHEAP (Low Income Home Energy Assistance Program)
    liheap = max(0.0, _try_vars(
        sim,
        "liheap",
        "liheap_benefit",
        "low_income_home_energy_assistance",
    ))

    income_tax_raw = _get(sim, "income_tax")
    state_tax_raw  = _get(sim, "state_income_tax")
    ss_tax  = max(0.0, _get(sim, "employee_social_security_tax"))
    mc_tax  = max(0.0, _get(sim, "employee_medicare_tax"))
    payroll_tax = ss_tax + mc_tax

    # Show EITC as its own positive bar; display pre-EITC federal burden
    federal_tax_pre_eitc = income_tax_raw + eitc

    net_income = _get(sim, "household_net_income")

    accounted = (
        annual_income
        + eitc + ctc + snap + medicaid_chip + aca_ptc
        + ssi + tanf + housing + ccdf + wic + school_meals + liheap
        - max(0.0, federal_tax_pre_eitc)
        - max(0.0, state_tax_raw)
        - payroll_tax
    )
    other_benefits = max(0.0, net_income - accounted)

    return {
        "eitc":             eitc,
        "child_tax_credit": ctc,
        "snap":             snap,
        "medicaid_chip":    medicaid_chip,
        "aca_ptc":          aca_ptc,
        "ssi":              ssi,
        "tanf":             tanf,
        "housing":          housing,
        "ccdf":             ccdf,
        "wic":              wic,
        "school_meals":     school_meals,
        "liheap":           liheap,
        "other_benefits":   other_benefits,
        "federal_tax":      -max(0.0, federal_tax_pre_eitc),
        "state_tax":        -max(0.0, state_tax_raw),
        "payroll_tax":      -payroll_tax,
        "net_income":       net_income,
    }


# ── Matched-household situation builder ───────────────────────────────────────

def _build_situation_matched(
    employment_income: float,
    n_adults: int,
    n_children: int,
    children_ages: list[int],
    spouse_annual_income: float,
    state_code: str,
) -> dict:
    """
    Build a PolicyEngine situation dict for a matched ASEC household.

    Unlike _build_situation() (which uses four stylised household types with
    zero spouse income and fixed child ages), this function takes real values
    drawn from a matched ASEC household:
      - n_adults              : 1 or 2
      - n_children            : 0–3 (children > 3 are truncated)
      - children_ages         : list of actual child ages (from ASEC)
      - spouse_annual_income  : ASEC-matched spouse's annual wage income ($)
      - state_code            : two-letter state abbreviation

    The primary earner's income is set to employment_income; the spouse's
    income is fixed at spouse_annual_income across the entire income grid
    (it is the matched household context, not a variable).
    """
    people: dict       = {}
    all_members: list  = []

    people["person1"] = {
        "age":               {YEAR_STR: 35},
        "employment_income": {YEAR_STR: employment_income},
    }
    all_members.append("person1")

    if n_adults == 2:
        people["person2"] = {
            "age":               {YEAR_STR: 33},
            "employment_income": {YEAR_STR: float(spouse_annual_income)},
        }
        all_members.append("person2")

    # Use actual child ages from the matched ASEC household (up to 3).
    # PE cares about age for CTC (<17), CCDF (<13), school meals (5-18), WIC.
    for i, child_age in enumerate(children_ages[:3]):
        cid = f"child{i + 1}"
        people[cid] = {
            "age":               {YEAR_STR: int(child_age)},
            "employment_income": {YEAR_STR: 0},
        }
        all_members.append(cid)

    adult_members = ["person1"] if n_adults == 1 else ["person1", "person2"]

    return {
        "people":        people,
        "families":      {"family1": {"members": all_members}},
        "marital_units": {"marital_unit1": {"members": adult_members}},
        "tax_units": {
            "tax_unit1": {
                "members":          all_members,
                "tax_unit_is_joint": {YEAR_STR: n_adults == 2},
            }
        },
        "spm_units":  {"spm_unit1": {"members": all_members}},
        "households": {
            "household1": {
                "members":     all_members,
                "state_code":  {YEAR_STR: state_code},
            }
        },
    }


def compute_income_point_matched(
    annual_income: float,
    n_adults: int,
    n_children: int,
    children_ages: list[int],
    spouse_annual_income: float,
    state_code: str,
) -> dict:
    """
    Run PolicyEngine for one primary-earner income level using real matched
    household context (actual spouse income and child ages from ASEC).

    Called by 02d_precompute_matched_schedules.py for each income grid point.
    """
    try:
        from policyengine_us import Simulation
    except ImportError as exc:
        raise RuntimeError(
            "policyengine-us is required. "
            "Install it with: pip install policyengine-us==1.592.4"
        ) from exc

    situation = _build_situation_matched(
        employment_income=annual_income,
        n_adults=n_adults,
        n_children=n_children,
        children_ages=children_ages,
        spouse_annual_income=spouse_annual_income,
        state_code=state_code,
    )
    sim = Simulation(situation=situation)
    return _extract_components(sim, annual_income)


# ── Public: single income point (used by pipeline) ───────────────────────────

def compute_income_point(
    annual_income: float,
    family_type: str,
    state_code: str,
) -> dict:
    """
    Run PolicyEngine for one annual income level and return decomposed components.
    Called by 01b_precompute_individual.py for each point in the income grid.
    """
    try:
        from policyengine_us import Simulation
    except ImportError as exc:
        raise RuntimeError(
            "policyengine-us is required for pipeline pre-computation. "
            "Install it with: pip install policyengine-us==1.592.4"
        ) from exc

    situation = _build_situation(annual_income, family_type, state_code)
    sim = Simulation(situation=situation)
    return _extract_components(sim, annual_income)


# ── Pre-computed schedule helpers ─────────────────────────────────────────────

def _schedule_path(family_type: str, state_code: str) -> Path:
    key = FAMILY_KEYS[family_type]
    return _SCHEDULES_DIR / f"{key}_{state_code}.parquet"


def schedules_available(family_type: str, state_code: str) -> bool:
    """Return True if the pre-computed parquet exists for this combination."""
    return _schedule_path(family_type, state_code).exists()


def _load_schedule(family_type: str, state_code: str) -> pd.DataFrame | None:
    path = _schedule_path(family_type, state_code)
    if not path.exists():
        return None
    return pd.read_parquet(path)


# ── Matched-household schedule helpers ───────────────────────────────────────

def matched_schedule_path(config_key: str, state_code: str) -> "Path":
    """Return the path for a matched-household pre-computed schedule parquet."""
    return _MATCHED_SCHEDULES_DIR / f"{config_key}_{state_code}.parquet"


def matched_schedule_available(config_key: str, state_code: str) -> bool:
    """Return True if the matched schedule parquet exists for this config."""
    return matched_schedule_path(config_key, state_code).exists()


def load_matched_schedule(config_key: str, state_code: str) -> "pd.DataFrame | None":
    """Load a matched-household schedule parquet, or None if not yet computed."""
    path = matched_schedule_path(config_key, state_code)
    if not path.exists():
        return None
    return pd.read_parquet(path)


def _discretise_child_age(age: int) -> int:
    if age <= 2:
        return 1
    if age <= 5:
        return 4
    if age <= 12:
        return 9
    return 15


def _discretise_spouse_income(spouse_income: float) -> float:
    x = max(0.0, float(spouse_income))
    for i, lo in enumerate(_SPOUSE_BUCKET_BOUNDS):
        hi = _SPOUSE_BUCKET_BOUNDS[i + 1] if i + 1 < len(_SPOUSE_BUCKET_BOUNDS) else float("inf")
        if lo <= x < hi:
            return float(_SPOUSE_BUCKET_REPRS[i])
    return float(_SPOUSE_BUCKET_REPRS[-1])


def _matched_config_key(
    n_adults: int,
    children_ages: list[int],
    spouse_annual_income: float,
) -> str:
    ages = [int(a) for a in children_ages if 0 <= int(a) <= 17][:3]
    ages_repr = tuple(sorted(_discretise_child_age(a) for a in ages))
    spouse_bucket = _discretise_spouse_income(spouse_annual_income)
    spouse_k = int(round(spouse_bucket / 1000.0))
    ages_str = "_".join(map(str, ages_repr)) if ages_repr else "none"
    return f"{n_adults}a_{len(ages)}c_{ages_str}_s{spouse_k}k"


def matched_schedule_available_for_inputs(
    marital_status: str,
    children_ages: list[int],
    spouse_annual_income: float,
    state_code: str,
) -> bool:
    n_adults = 2 if str(marital_status).lower().startswith("married") else 1
    config_key = _matched_config_key(
        n_adults=n_adults,
        children_ages=children_ages,
        spouse_annual_income=spouse_annual_income,
    )
    return matched_schedule_available(config_key, state_code)


# ── Public: build budget constraint DataFrame ─────────────────────────────────

def run_from_precomputed(
    employer_wage: float,
    family_type: str,
    state_code: str,
    subsidy_params: dict,
) -> pd.DataFrame:
    """
    Build the budget constraint DataFrame using pre-computed income schedules
    (fast path) or live PolicyEngine calls (fallback).

    Returns a flat DataFrame with columns:
        annual_hours, scenario, employer_wages, wage_subsidy, <component cols>
    """
    schedule = _load_schedule(family_type, state_code)

    if schedule is None:
        # Fallback: live computation (slow, but works without pre-computed data)
        return _run_live(employer_wage, family_type, state_code, subsidy_params)

    from utils.subsidy import hourly_subsidy

    sub_hr = hourly_subsidy(employer_wage, **subsidy_params)
    income_axis = schedule.index.values.astype(float)

    rows = []
    for annual_hours in HOURS_CONTINUOUS:
        for with_subsidy, scenario in [(False, "Baseline"), (True, "With Subsidy")]:
            sw = sub_hr if with_subsidy else 0.0
            employer_wages_annual = employer_wage * annual_hours
            wage_subsidy_annual   = sw * annual_hours
            total_income          = employer_wages_annual + wage_subsidy_annual

            row: dict = {
                "annual_hours":  annual_hours,
                "scenario":      scenario,
                "employer_wages": employer_wages_annual,
                "wage_subsidy":   wage_subsidy_annual,
            }
            for col in _SCHEDULE_COLS:
                row[col] = float(np.interp(total_income, income_axis, schedule[col].values))

            # PolicyEngine's household_net_income excludes in-kind health subsidies
            # (ACA premium tax credits, Medicaid/CHIP) because they are not cash
            # income. Add them back so the net_income line equals the sum of all
            # displayed bars.
            row["net_income"] = (
                row["net_income"]
                + row.get("aca_ptc", 0.0)
                + row.get("medicaid_chip", 0.0)
            )

            rows.append(row)

    return pd.DataFrame(rows)


def _run_live_matched(
    employer_wage: float,
    n_adults: int,
    children_ages: list[int],
    spouse_annual_income: float,
    state_code: str,
    subsidy_params: dict,
) -> pd.DataFrame:
    try:
        from policyengine_us import Simulation
    except ImportError as exc:
        raise RuntimeError(
            "PolicyEngine is not installed in this environment and no matched pre-computed "
            "schedule was found for this household configuration."
        ) from exc
    from utils.subsidy import hourly_subsidy

    sub_hr = hourly_subsidy(employer_wage, **subsidy_params)
    rows = []
    for annual_hours in HOURS_CONTINUOUS:
        for with_subsidy, scenario in [(False, "Baseline"), (True, "With Subsidy")]:
            sw = sub_hr if with_subsidy else 0.0
            employer_wages_annual = employer_wage * annual_hours
            wage_subsidy_annual = sw * annual_hours
            total_income = employer_wages_annual + wage_subsidy_annual

            situation = _build_situation_matched(
                employment_income=total_income,
                n_adults=n_adults,
                n_children=min(len(children_ages), 3),
                children_ages=children_ages,
                spouse_annual_income=spouse_annual_income,
                state_code=state_code,
            )
            sim = Simulation(situation=situation)
            components = _extract_components(sim, total_income)
            components["net_income"] = (
                components["net_income"]
                + components.get("aca_ptc", 0.0)
                + components.get("medicaid_chip", 0.0)
            )
            rows.append({
                "annual_hours": annual_hours,
                "scenario": scenario,
                "employer_wages": employer_wages_annual,
                "wage_subsidy": wage_subsidy_annual,
                **components,
            })
    return pd.DataFrame(rows)


def run_from_matched_precomputed(
    employer_wage: float,
    marital_status: str,
    children_ages: list[int],
    spouse_annual_income: float,
    state_code: str,
    subsidy_params: dict,
) -> pd.DataFrame:
    n_adults = 2 if str(marital_status).lower().startswith("married") else 1
    ages_clean = [int(a) for a in children_ages if 0 <= int(a) <= 17][:3]
    spouse_income_clean = max(0.0, float(spouse_annual_income or 0.0))
    config_key = _matched_config_key(n_adults, ages_clean, spouse_income_clean)
    schedule = load_matched_schedule(config_key, state_code)

    if schedule is None:
        return _run_live_matched(
            employer_wage=employer_wage,
            n_adults=n_adults,
            children_ages=ages_clean,
            spouse_annual_income=spouse_income_clean,
            state_code=state_code,
            subsidy_params=subsidy_params,
        )

    from utils.subsidy import hourly_subsidy

    sub_hr = hourly_subsidy(employer_wage, **subsidy_params)
    income_axis = schedule.index.values.astype(float)
    rows = []
    for annual_hours in HOURS_CONTINUOUS:
        for with_subsidy, scenario in [(False, "Baseline"), (True, "With Subsidy")]:
            sw = sub_hr if with_subsidy else 0.0
            employer_wages_annual = employer_wage * annual_hours
            wage_subsidy_annual = sw * annual_hours
            total_income = employer_wages_annual + wage_subsidy_annual

            row = {
                "annual_hours": annual_hours,
                "scenario": scenario,
                "employer_wages": employer_wages_annual,
                "wage_subsidy": wage_subsidy_annual,
            }
            for col in _SCHEDULE_COLS:
                row[col] = float(np.interp(total_income, income_axis, schedule[col].values))
            row["net_income"] = (
                row["net_income"]
                + row.get("aca_ptc", 0.0)
                + row.get("medicaid_chip", 0.0)
            )
            rows.append(row)
    return pd.DataFrame(rows)


def _run_live(
    employer_wage: float,
    family_type: str,
    state_code: str,
    subsidy_params: dict,
) -> pd.DataFrame:
    """Live PolicyEngine fallback — runs 314 simulations (one per hour bin × scenario)."""
    try:
        from policyengine_us import Simulation
    except ImportError as exc:
        raise RuntimeError(
            "PolicyEngine is not installed in this environment. "
            "Pre-computed schedules should cover all 204 state/family combinations — "
            "check that the individual_schedules/ parquets are present in the repo."
        ) from exc
    from utils.subsidy import hourly_subsidy

    sub_hr = hourly_subsidy(employer_wage, **subsidy_params)

    rows = []
    for annual_hours in HOURS_CONTINUOUS:
        for with_subsidy, scenario in [(False, "Baseline"), (True, "With Subsidy")]:
            sw = sub_hr if with_subsidy else 0.0
            employer_wages_annual = employer_wage * annual_hours
            wage_subsidy_annual   = sw * annual_hours
            total_income          = employer_wages_annual + wage_subsidy_annual

            situation = _build_situation(total_income, family_type, state_code)
            sim = Simulation(situation=situation)
            components = _extract_components(sim, total_income)

            components["net_income"] = (
                components["net_income"]
                + components.get("aca_ptc", 0.0)
                + components.get("medicaid_chip", 0.0)
            )
            row = {
                "annual_hours":   annual_hours,
                "scenario":       scenario,
                "employer_wages": employer_wages_annual,
                "wage_subsidy":   wage_subsidy_annual,
                **components,
            }
            rows.append(row)

    return pd.DataFrame(rows)
