"""
Household-level PolicyEngine simulation for the budget constraint figure.

Two execution modes:
  1. Pre-computed (fast, deployment-ready): load parquet schedules generated by
     WORKSPACE/code/01_data_preparation/01b_precompute_individual.py, then
     interpolate at runtime — no PolicyEngine calls needed.

  2. Live (development fallback): call PolicyEngine directly for every hour bin.
     Slow on first load (~1-3 min) but cached by Streamlit.

Public API
----------
run_from_precomputed(employer_wage, family_type, state_code, subsidy_params)
    → pd.DataFrame   (used by the app; auto-selects mode)

compute_income_point(annual_income, family_type, state_code)
    → dict           (used by the pre-computation pipeline)
"""
from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

# ── Hours axes ────────────────────────────────────────────────────────────────

# Continuous x-axis for the budget constraint figure
HOURS_CONTINUOUS: list[int] = list(range(0, 3121, 20))

# Reference bins used by the difference table
TABLE_HOURS: dict[int, str] = {
    0:    "0 hrs/wk",
    1040: "20 hrs/wk",
    2080: "40 hrs/wk",
    3120: "60 hrs/wk",
}

# ── Family types ──────────────────────────────────────────────────────────────

FAMILY_TYPES: dict[str, dict] = {
    "Single adult, no children":   {"adults": 1, "children": 0},
    "Single adult, 2 children":    {"adults": 1, "children": 2},
    "Married couple, no children": {"adults": 2, "children": 0},
    "Married couple, 2 children":  {"adults": 2, "children": 2},
}

# Short keys used in parquet filenames
FAMILY_KEYS: dict[str, str] = {
    "Single adult, no children":   "single_0c",
    "Single adult, 2 children":    "single_2c",
    "Married couple, no children": "married_0c",
    "Married couple, 2 children":  "married_2c",
}

YEAR_STR = "2025"

# ── Income components (display order + chart colors) ─────────────────────────

COMPONENTS = [
    # (key, label, color, is_positive)
    # Colors drawn from EIG brand palette (eig_tokens.py).
    # Primary / secondary brand colors used for main series.
    # Minor series (wic, school_meals, liheap, other_benefits) use
    # EIG-derived tints — acceptable brand extension for dense categoricals.
    # Tax bars use EIG red sequential scale (eig_seq_red_5).
    ("employer_wages",   "Employer wages",        "#194F8B", True),   # eig_blue_800
    ("wage_subsidy",     "Wage subsidy",          "#19644D", True),   # eig_green_700
    ("eitc",             "EITC",                 "#E1AD28", True),   # eig_gold_600
    ("child_tax_credit", "Child tax credit",     "#176F96", True),   # eig_cyan_700
    ("snap",             "SNAP",                 "#D6936F", True),   # eig_tan_500
    ("medicaid_chip",    "Medicaid / CHIP",      "#024140", True),   # eig_teal_900
    ("aca_ptc",          "ACA health subsidies", "#5E9C86", True),   # eig_green_500
    ("ssi",              "SSI",                  "#39274F", True),   # eig_purple_800
    ("tanf",             "TANF",                 "#F0B799", True),   # eig_tan_300
    ("housing",          "Section 8 / Housing",  "#B3D6DD", True),   # eig_blue_200
    ("ccdf",             "Child care (CCDF)",    "#A89F94", True),   # warm gray (brand guidelines)
    ("wic",              "WIC",                  "#8BBF9F", True),   # tint of eig_green_700
    ("school_meals",     "School meals",         "#8FA5BD", True),   # tint of eig_blue_800
    ("liheap",           "LIHEAP (energy)",      "#7B6B8A", True),   # tint of eig_purple_800
    ("other_benefits",   "Other benefits",       "#C5C0BB", True),   # warm neutral tint
    ("federal_tax",      "Federal income tax",   "#97310E", False),  # eig_seq_red_5[0]
    ("state_tax",        "State income tax",     "#D34917", False),  # eig_seq_red_5[1]
    ("payroll_tax",      "Payroll taxes",        "#F97D1E", False),  # eig_seq_red_5[2]
]

# Component keys that represent government-funded transfers
TRANSFER_KEYS = [
    "wage_subsidy", "eitc", "child_tax_credit",
    "snap", "medicaid_chip", "aca_ptc", "ssi", "tanf", "housing",
    "ccdf", "wic", "school_meals", "liheap", "other_benefits",
]

# Columns stored in each parquet schedule (analytic cols excluded)
_SCHEDULE_COLS = [
    "eitc", "child_tax_credit", "snap", "medicaid_chip", "aca_ptc",
    "ssi", "tanf", "housing", "ccdf", "wic", "school_meals", "liheap",
    "other_benefits", "federal_tax", "state_tax", "payroll_tax", "net_income",
]

# Path to pre-computed schedules (relative to this file)
_SCHEDULES_DIR: Path = (
    Path(__file__).resolve().parent  # utils/
    .parent                          # app/
    .parent                          # WORKSPACE/
    / "output" / "data" / "intermediate_results" / "individual_schedules"
)


# ── PolicyEngine helpers ──────────────────────────────────────────────────────

def _build_situation(
    employment_income: float,
    family_type: str,
    state_code: str,
) -> dict:
    cfg = FAMILY_TYPES[family_type]
    n_adults = cfg["adults"]
    n_children = cfg["children"]

    people: dict = {}
    all_members: list[str] = []

    people["person1"] = {
        "age": {YEAR_STR: 35},
        "employment_income": {YEAR_STR: employment_income},
    }
    all_members.append("person1")

    if n_adults == 2:
        people["person2"] = {
            "age": {YEAR_STR: 33},
            "employment_income": {YEAR_STR: 0},
        }
        all_members.append("person2")

    child_ages = [8, 3, 6, 1]
    for i in range(n_children):
        cid = f"child{i + 1}"
        people[cid] = {
            "age": {YEAR_STR: child_ages[i]},
            "employment_income": {YEAR_STR: 0},
        }
        all_members.append(cid)

    adult_members = ["person1"] if n_adults == 1 else ["person1", "person2"]

    return {
        "people": people,
        "families": {"family1": {"members": all_members}},
        "marital_units": {"marital_unit1": {"members": adult_members}},
        "tax_units": {
            "tax_unit1": {
                "members": all_members,
                "tax_unit_is_joint": {YEAR_STR: n_adults == 2},
            }
        },
        "spm_units": {"spm_unit1": {"members": all_members}},
        "households": {
            "household1": {
                "members": all_members,
                "state_code": {YEAR_STR: state_code},
            }
        },
    }


def _get(sim, var: str) -> float:
    """Sum a PolicyEngine variable across all entity instances. Returns 0 on error."""
    try:
        return float(sim.calculate(var, YEAR_STR).sum())
    except Exception:
        return 0.0


def _try_vars(sim, *vars: str) -> float:
    """Try variable names in order; return the first non-zero result."""
    for var in vars:
        val = _get(sim, var)
        if val != 0.0:
            return val
    return 0.0


def _extract_components(sim, annual_income: float) -> dict:
    """
    Extract benefit/tax components from a PolicyEngine Simulation object.
    employer_wages and wage_subsidy are NOT included — those are analytic.
    """
    eitc    = max(0.0, _get(sim, "eitc"))
    ctc     = max(0.0, _try_vars(sim, "refundable_ctc", "child_tax_credit_refundable",
                                 "additional_child_tax_credit"))
    snap    = max(0.0, _get(sim, "snap"))

    # Medicaid / CHIP: imputed dollar value of coverage.
    # PolicyEngine-US computes per-enrollee costs from actuarial data.
    # We try several variable name patterns used across PE-US versions.
    medicaid_chip = max(0.0, _try_vars(
        sim,
        "medicaid_and_chip",
        "medicaid",
        "medicaid_benefit",
        "medicaid_and_chip_benefit",
    ))

    # ACA Premium Tax Credits (marketplace health insurance subsidies)
    aca_ptc = max(0.0, _try_vars(
        sim,
        "premium_tax_credit",
        "aca_premium_tax_credit",
        "ptc",
    ))

    ssi     = max(0.0, _get(sim, "ssi"))
    tanf    = max(0.0, _try_vars(sim, "tanf", "tanf_max_benefit"))

    # Section 8 / Housing Choice Vouchers and other housing assistance
    housing = max(0.0, _try_vars(
        sim,
        "housing_assistance",
        "section_8_housing_assistance",
        "housing_choice_voucher",
        "section_8",
    ))

    # Child care subsidies (CCDF)
    ccdf = max(0.0, _try_vars(
        sim,
        "ccdf_subsidy",
        "ccdf",
        "child_care_subsidy",
        "child_care_and_development_fund",
    ))

    # WIC (Women, Infants, and Children nutrition program)
    wic = max(0.0, _try_vars(
        sim,
        "wic",
        "wic_benefit",
    ))

    # Free / reduced-price school meals (NSLP)
    school_meals = max(0.0, _try_vars(
        sim,
        "school_meal_subsidy",
        "nslp",
        "free_school_meals",
        "school_lunch_subsidy",
        "free_and_reduced_price_school_meals",
    ))

    # LIHEAP (Low Income Home Energy Assistance Program)
    liheap = max(0.0, _try_vars(
        sim,
        "liheap",
        "liheap_benefit",
        "low_income_home_energy_assistance",
    ))

    income_tax_raw = _get(sim, "income_tax")
    state_tax_raw  = _get(sim, "state_income_tax")
    ss_tax  = max(0.0, _get(sim, "employee_social_security_tax"))
    mc_tax  = max(0.0, _get(sim, "employee_medicare_tax"))
    payroll_tax = ss_tax + mc_tax

    # Show EITC as its own positive bar; display pre-EITC federal burden
    federal_tax_pre_eitc = income_tax_raw + eitc

    net_income = _get(sim, "household_net_income")

    accounted = (
        annual_income
        + eitc + ctc + snap + medicaid_chip + aca_ptc
        + ssi + tanf + housing + ccdf + wic + school_meals + liheap
        - max(0.0, federal_tax_pre_eitc)
        - max(0.0, state_tax_raw)
        - payroll_tax
    )
    other_benefits = max(0.0, net_income - accounted)

    return {
        "eitc":             eitc,
        "child_tax_credit": ctc,
        "snap":             snap,
        "medicaid_chip":    medicaid_chip,
        "aca_ptc":          aca_ptc,
        "ssi":              ssi,
        "tanf":             tanf,
        "housing":          housing,
        "ccdf":             ccdf,
        "wic":              wic,
        "school_meals":     school_meals,
        "liheap":           liheap,
        "other_benefits":   other_benefits,
        "federal_tax":      -max(0.0, federal_tax_pre_eitc),
        "state_tax":        -max(0.0, state_tax_raw),
        "payroll_tax":      -payroll_tax,
        "net_income":       net_income,
    }


# ── Public: single income point (used by pipeline) ───────────────────────────

def compute_income_point(
    annual_income: float,
    family_type: str,
    state_code: str,
) -> dict:
    """
    Run PolicyEngine for one annual income level and return decomposed components.
    Called by 01b_precompute_individual.py for each point in the income grid.
    """
    try:
        from policyengine_us import Simulation
    except ImportError as exc:
        raise RuntimeError(
            "policyengine-us is required for pipeline pre-computation. "
            "Install it with: pip install policyengine-us==1.592.4"
        ) from exc

    situation = _build_situation(annual_income, family_type, state_code)
    sim = Simulation(situation=situation)
    return _extract_components(sim, annual_income)


# ── Pre-computed schedule helpers ─────────────────────────────────────────────

def _schedule_path(family_type: str, state_code: str) -> Path:
    key = FAMILY_KEYS[family_type]
    return _SCHEDULES_DIR / f"{key}_{state_code}.parquet"


def schedules_available(family_type: str, state_code: str) -> bool:
    """Return True if the pre-computed parquet exists for this combination."""
    return _schedule_path(family_type, state_code).exists()


def _load_schedule(family_type: str, state_code: str) -> pd.DataFrame | None:
    path = _schedule_path(family_type, state_code)
    if not path.exists():
        return None
    return pd.read_parquet(path)


# ── Public: build budget constraint DataFrame ─────────────────────────────────

def run_from_precomputed(
    employer_wage: float,
    family_type: str,
    state_code: str,
    subsidy_params: dict,
) -> pd.DataFrame:
    """
    Build the budget constraint DataFrame using pre-computed income schedules
    (fast path) or live PolicyEngine calls (fallback).

    Returns a flat DataFrame with columns:
        annual_hours, scenario, employer_wages, wage_subsidy, <component cols>
    """
    schedule = _load_schedule(family_type, state_code)

    if schedule is None:
        # Fallback: live computation (slow, but works without pre-computed data)
        return _run_live(employer_wage, family_type, state_code, subsidy_params)

    from utils.subsidy import hourly_subsidy

    sub_hr = hourly_subsidy(employer_wage, **subsidy_params)
    income_axis = schedule.index.values.astype(float)

    rows = []
    for annual_hours in HOURS_CONTINUOUS:
        for with_subsidy, scenario in [(False, "Baseline"), (True, "With Subsidy")]:
            sw = sub_hr if with_subsidy else 0.0
            employer_wages_annual = employer_wage * annual_hours
            wage_subsidy_annual   = sw * annual_hours
            total_income          = employer_wages_annual + wage_subsidy_annual

            row: dict = {
                "annual_hours":  annual_hours,
                "scenario":      scenario,
                "employer_wages": employer_wages_annual,
                "wage_subsidy":   wage_subsidy_annual,
            }
            for col in _SCHEDULE_COLS:
                row[col] = float(np.interp(total_income, income_axis, schedule[col].values))

            rows.append(row)

    return pd.DataFrame(rows)


def _run_live(
    employer_wage: float,
    family_type: str,
    state_code: str,
    subsidy_params: dict,
) -> pd.DataFrame:
    """Live PolicyEngine fallback — runs 314 simulations (one per hour bin × scenario)."""
    try:
        from policyengine_us import Simulation
    except ImportError as exc:
        raise RuntimeError(
            "PolicyEngine is not installed in this environment. "
            "Pre-computed schedules should cover all 204 state/family combinations — "
            "check that the individual_schedules/ parquets are present in the repo."
        ) from exc
    from utils.subsidy import hourly_subsidy

    sub_hr = hourly_subsidy(employer_wage, **subsidy_params)

    rows = []
    for annual_hours in HOURS_CONTINUOUS:
        for with_subsidy, scenario in [(False, "Baseline"), (True, "With Subsidy")]:
            sw = sub_hr if with_subsidy else 0.0
            employer_wages_annual = employer_wage * annual_hours
            wage_subsidy_annual   = sw * annual_hours
            total_income          = employer_wages_annual + wage_subsidy_annual

            situation = _build_situation(total_income, family_type, state_code)
            sim = Simulation(situation=situation)
            components = _extract_components(sim, total_income)

            row = {
                "annual_hours":   annual_hours,
                "scenario":       scenario,
                "employer_wages": employer_wages_annual,
                "wage_subsidy":   wage_subsidy_annual,
                **components,
            }
            rows.append(row)

    return pd.DataFrame(rows)
