"""
Tab 2: Population-level impacts.
Shows pre-computed PolicyEngine microsimulation results.
Results are loaded from WORKSPACE/output/data/intermediate_results/population_impacts.parquet
(generated by WORKSPACE/code/02_descriptive_analysis/02a_descriptive_stats.py).

If the pre-computed file is not yet available, falls back to a message guiding the user
to run the pipeline first.
"""

from __future__ import annotations

import sys
from pathlib import Path

import streamlit as st

# Resolve project root so we can import config
_here = Path(__file__).resolve()
_project_root = _here.parents[4]  # WORKSPACE/app/tabs -> project root
if str(_project_root) not in sys.path:
    sys.path.insert(0, str(_project_root / "WORKSPACE" / "code" / "00_setup"))

_RESULTS_PATH = (
    _project_root
    / "WORKSPACE"
    / "output"
    / "data"
    / "intermediate_results"
    / "population_impacts.parquet"
)


def render() -> None:
    st.header("Population-Level Impacts")
    st.markdown(
        "These results are computed using the "
        "[PolicyEngine-US](https://policyengine.org) microsimulation engine "
        "on nationally representative household data."
    )

    if not _RESULTS_PATH.exists():
        st.warning(
            "Population impact data has not been generated yet. "
            "Run the data pipeline to compute results:\n\n"
            "```bash\npython WORKSPACE/code/run_all.py\n```"
        )
        st.markdown(
            "### What this tab will show\n"
            "- **Total annual cost** of the wage subsidy\n"
            "- **Number of workers** benefiting by wage bracket\n"
            "- **Average subsidy** by income decile\n"
            "- **Demographic breakdown** (gender, race, state)\n"
            "- **Effective marginal tax rate** comparison vs. EITC"
        )
        return

    import pandas as pd
    import plotly.express as px

    df = pd.read_parquet(_RESULTS_PATH)

    st.subheader("Key Statistics")
    col1, col2, col3 = st.columns(3)
    if "total_cost_bn" in df.columns:
        col1.metric("Total annual cost", f"${df['total_cost_bn'].iloc[0]:.1f}B")
    if "n_workers_mn" in df.columns:
        col2.metric("Workers benefiting", f"{df['n_workers_mn'].iloc[0]:.1f}M")
    if "avg_annual_subsidy" in df.columns:
        col3.metric("Avg. annual subsidy", f"${df['avg_annual_subsidy'].iloc[0]:,.0f}")

    # Placeholder for chart — will be built once pipeline runs
    st.info(
        "Detailed charts will render automatically once the pipeline has been run "
        "and population_impacts.parquet is present."
    )
