#!/usr/bin/env python3
"""Generate language-specific token files from canonical EIG token JSON."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
TOKEN_PATH = ROOT / "tokens" / "eig-style-tokens.v1.json"
OUT_PY = ROOT / "themes" / "python" / "eig_tokens.py"
OUT_R = ROOT / "themes" / "r" / "eig_tokens.R"
OUT_DO = ROOT / "themes" / "stata" / "eig_tokens.do"

DISCRETE_ORDER = [
    "eig_teal_900",
    "eig_blue_800",
    "eig_green_500",
    "eig_gold_600",
    "eig_purple_800",
    "eig_cyan_700",
    "eig_tan_500",
]


def _load_tokens() -> dict[str, Any]:
    return json.loads(TOKEN_PATH.read_text(encoding="utf-8"))


def _brand(tokens: dict[str, Any]) -> list[dict[str, Any]]:
    return tokens["colors"]["brand"]


def _sequential(tokens: dict[str, Any]) -> list[dict[str, Any]]:
    return tokens["colors"]["sequential"]


def _legacy_sets(tokens: dict[str, Any]) -> list[dict[str, Any]]:
    return tokens["colors"]["legacy_semantic_sets"]


def _safe_key(key: str) -> str:
    chars = []
    for ch in key:
        if ch.isalnum():
            chars.append(ch.upper())
        else:
            chars.append("_")
    return "".join(chars)


def _python_literal(value: Any) -> str:
    return json.dumps(value, indent=2, sort_keys=True)


def _write_python(tokens: dict[str, Any]) -> None:
    brand = {c["id"]: c["hex"] for c in _brand(tokens)}
    brand_rgb = {c["id"]: c["rgb"] for c in _brand(tokens)}
    sequential = {s["id"]: s["entries"] for s in _sequential(tokens)}
    legacy = {s["set_id"]: s["entries"] for s in _legacy_sets(tokens)}
    typography = tokens["typography"]
    sizing = tokens["sizing"]
    policies = tokens["policies"]
    status_by_id = {c["id"]: c["status"] for c in _brand(tokens)}
    provisional = [k for k, v in status_by_id.items() if v == "provisional"]
    discrete = [brand[k] for k in DISCRETE_ORDER if k in brand]

    content = f"""# Auto-generated by scripts/sync_tokens.py. Do not edit manually.
# Source: tokens/eig-style-tokens.v1.json

TOKENS_VERSION = {_python_literal(tokens["meta"]["version"])}
TOKENS_GENERATED_ON = {_python_literal(tokens["meta"]["generated_on"])}

BRAND_COLORS = {_python_literal(brand)}
BRAND_RGB = {_python_literal(brand_rgb)}
BRAND_STATUS = {_python_literal(status_by_id)}
PROVISIONAL_TOKEN_IDS = {_python_literal(provisional)}

EIG_DISCRETE = {_python_literal(discrete)}
SEQUENTIAL = {_python_literal(sequential)}
LEGACY_SEMANTIC_SETS = {_python_literal(legacy)}

TYPOGRAPHY = {_python_literal(typography)}
SIZING = {_python_literal(sizing)}
POLICIES = {_python_literal(policies)}
"""
    OUT_PY.write_text(content, encoding="utf-8")


def _r_vector(name: str, mapping: dict[str, str]) -> str:
    parts = [f'"{k}" = "{v}"' for k, v in mapping.items()]
    return f'{name} <- c(\n  ' + ",\n  ".join(parts) + "\n)\n"


def _r_list(name: str, mapping: dict[str, Any], indent: int = 0) -> str:
    pad = " " * indent
    pieces = []
    for key, value in mapping.items():
        if isinstance(value, dict):
            nested = _r_list("", value, indent=indent + 2).strip()
            value_str = nested.replace("\n", "\n" + pad + "  ")
            pieces.append(f'{pad}  "{key}" = {value_str}')
        elif isinstance(value, list):
            arr = ', '.join(f'"{v}"' if isinstance(v, str) else str(v) for v in value)
            pieces.append(f'{pad}  "{key}" = c({arr})')
        elif isinstance(value, str):
            pieces.append(f'{pad}  "{key}" = "{value}"')
        else:
            pieces.append(f'{pad}  "{key}" = {value}')
    if name:
        header = f"{name} <- list(\n"
    else:
        header = "list(\n"
    return header + ",\n".join(pieces) + f"\n{pad})"


def _write_r(tokens: dict[str, Any]) -> None:
    brand = {c["id"]: c["hex"] for c in _brand(tokens)}
    sequential = {s["id"]: s["entries"] for s in _sequential(tokens)}
    legacy = {s["set_id"]: s["entries"] for s in _legacy_sets(tokens)}
    discrete = [brand[k] for k in DISCRETE_ORDER if k in brand]
    provisional = [c["id"] for c in _brand(tokens) if c["status"] == "provisional"]
    headline = tokens["typography"]["headline"]["primary_family"]
    body = tokens["typography"]["body"]["primary_family"]
    fig = tokens["sizing"]["figure_default"]
    legacy_rule = tokens["policies"]["legacy_palette_decision_rule"]

    lines = [
        "# Auto-generated by scripts/sync_tokens.py. Do not edit manually.",
        "# Source: tokens/eig-style-tokens.v1.json",
        "",
        f'EIG_TOKENS_VERSION <- "{tokens["meta"]["version"]}"',
        f'EIG_TOKENS_GENERATED_ON <- "{tokens["meta"]["generated_on"]}"',
        "",
        _r_vector("EIG_COLORS", brand).rstrip(),
        "",
    ]

    lines.append("EIG_DISCRETE <- c(" + ", ".join(f'"{x}"' for x in discrete) + ")")
    lines.append("")
    lines.append(
        "EIG_PROVISIONAL_TOKEN_IDS <- c(" + ", ".join(f'"{x}"' for x in provisional) + ")"
    )
    lines.append("")
    lines.append(_r_list("EIG_SEQUENTIAL", sequential))
    lines.append("")
    lines.append(_r_list("EIG_LEGACY_SEMANTIC_SETS", legacy))
    lines.append("")
    lines.append(f'EIG_FONT_HEADLINE_PRIMARY <- "{headline}"')
    lines.append(f'EIG_FONT_BODY_PRIMARY <- "{body}"')
    lines.append("")
    lines.append(f'EIG_FIGURE_DEFAULT_WIDTH_IN <- {fig["width_in"]}')
    lines.append(f'EIG_FIGURE_DEFAULT_HEIGHT_IN <- {fig["height_in"]}')
    lines.append("")
    lines.append(
        "EIG_LEGACY_PALETTE_DECISION_RULE <- c("
        + ", ".join(f'"{x}"' for x in legacy_rule)
        + ")"
    )
    lines.append("")
    OUT_R.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _write_stata(tokens: dict[str, Any]) -> None:
    brand = _brand(tokens)
    sequential = _sequential(tokens)
    legacy = _legacy_sets(tokens)

    lines = [
        "* Auto-generated by scripts/sync_tokens.py. Do not edit manually.",
        "* Source: tokens/eig-style-tokens.v1.json",
        f'* Version: {tokens["meta"]["version"]}',
        "",
    ]

    for c in brand:
        key = _safe_key(c["id"])
        hex_value = c["hex"]
        rgb_value = " ".join(str(x) for x in c["rgb"])
        lines.append(f'global EIG_HEX_{key} "{hex_value}"')
        lines.append(f'global EIG_RGB_{key} "{rgb_value}"')
        lines.append(f'global EIG_STATUS_{key} "{c["status"]}"')
    lines.append("")

    discrete_hex = []
    brand_by_id = {c["id"]: c for c in brand}
    for token_id in DISCRETE_ORDER:
        if token_id in brand_by_id:
            discrete_hex.append(brand_by_id[token_id]["hex"])
    lines.append(f'global EIG_DISCRETE_HEX "{" ".join(discrete_hex)}"')
    lines.append("")

    for seq in sequential:
        key = _safe_key(seq["id"])
        joined = " ".join(seq["entries"])
        lines.append(f'global EIG_SEQ_{key} "{joined}"')
    lines.append("")

    for set_item in legacy:
        set_key = _safe_key(set_item["set_id"])
        for name, color in set_item["entries"].items():
            entry_key = _safe_key(name)
            lines.append(f'global EIG_LEGACY_{set_key}_{entry_key} "{color}"')
    lines.append("")

    headline = tokens["typography"]["headline"]["primary_family"]
    body = tokens["typography"]["body"]["primary_family"]
    lines.append(f'global EIG_FONT_HEADLINE "{headline}"')
    lines.append(f'global EIG_FONT_BODY "{body}"')
    lines.append("")

    fig = tokens["sizing"]["figure_default"]
    lines.append(f'global EIG_FIG_WIDTH_IN {fig["width_in"]}')
    lines.append(f'global EIG_FIG_HEIGHT_IN {fig["height_in"]}')
    lines.append("")

    OUT_DO.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    tokens = _load_tokens()
    _write_python(tokens)
    _write_r(tokens)
    _write_stata(tokens)
    print("Synced token outputs:")
    print(f"  - {OUT_PY.relative_to(ROOT)}")
    print(f"  - {OUT_R.relative_to(ROOT)}")
    print(f"  - {OUT_DO.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
