"""
05b_state_choropleth.py -- Figure 1: average annual subsidy per eligible worker by state.

.. deprecated:: 2026-07-08
   SUPERSEDED by the R figure suite. Figure 1 is now generated by
   ``code/05_figures_tables/05c_core_figures.R::fig1_choropleth`` (tigris + sf + the canonical
   EIG R theme), so the whole publication figure set (Figures 1-13) is one R/ggplot2 system.
   This Python/plotly version is retained only as the pattern source for the Streamlit app's
   interactive choropleth (``app/tabs/population.py``); it is NOT wired into ``run_all.py`` and
   its PNG/SVG outputs are overwritten by the R version. Do not run both for the same file.

Renders a publication-ready US state choropleth of ``avg_annual_subsidy`` from the
population simulation and writes both a PNG (300 dpi) and an SVG to
``output/figures/main/``.

Design provenance
-----------------
This figure deliberately REUSES the choropleth pattern already established in the
Streamlit app (``app/tabs/population.py::_make_choropleth``, the "Avg. annual subsidy ($)"
branch) so the static figure and the interactive app stay visually identical:

  * colorscale  : eig_cream_100 (#FEECD6) -> eig_gold_600 (#E1AD28)  (light = low, dark = high)
  * geo         : locationmode "USA-states", scope "usa", white state borders (0.5),
                  no lakes, white background, #F5F5F5 land
  * layout      : app/utils/eig_style.py::eig_plotly_layout (EIG fonts + brand colors)

All colors are token-derived (Infrastructure/style tokens, surfaced via BRAND_COLORS).
Per EIG figure-style rules: no boxed plot border, a "Figure N." + sentence-case title,
and a source line embedded as a bottom annotation. Gridlines are not applicable to a map.

Usage
-----
    .venv/bin/python code/05_figures_tables/05b_state_choropleth.py

Assumptions
-----------
  * ``output/data/intermediate_results/population/by_state.parquet`` exists (51 rows incl. DC)
    with columns ``state_code`` and ``avg_annual_subsidy``. It is produced by the
    descriptive-analysis stage of the pipeline; this script does not regenerate it.
  * DC is retained in the data. On a state choropleth its polygon is too small to read,
    so it is called out with a small labeled marker and a note (see DC_NOTE below).
"""
from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

import pandas as pd
import plotly.graph_objects as go

# ── Locate project root and load canonical config ──────────────────────────────
_HERE = Path(__file__).resolve()
# code/05_figures_tables/05b_state_choropleth.py -> repo root is parents[2]
PROJECT = _HERE.parents[2]

_CONFIG_PATH = PROJECT / "code" / "00_setup" / "00_config.py"
_spec = importlib.util.spec_from_file_location("eig_config", _CONFIG_PATH)
_config = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_config)  # type: ignore[union-attr]

PATH_OUTPUT_FIG_MAIN = _config.PATH_OUTPUT_FIG_MAIN
FIG_DPI = _config.cfg["fig_dpi"]

# ── Reuse the app's EIG Plotly styling helpers ─────────────────────────────────
_APP = PROJECT / "app"
if str(_APP) not in sys.path:
    sys.path.insert(0, str(_APP))
from utils.eig_style import eig_plotly_layout, BRAND_COLORS  # noqa: E402

# ── Constants ──────────────────────────────────────────────────────────────────
BY_STATE_PARQUET = (
    PROJECT / "output" / "data" / "intermediate_results" / "population" / "by_state.parquet"
)
FIG_STEM = "fig1_avg_subsidy_by_state"

TITLE = "Figure 1. Average annual subsidy per eligible worker by state"
SOURCE_LINE = "Source: Economic Innovation Group 80-80 wage subsidy simulation, 2026."
COLORBAR_TITLE = "Avg. annual subsidy, $/yr"

# Reused exactly from app/tabs/population.py (avg_annual_subsidy branch):
COLOR_SCALE = [
    [0.0, BRAND_COLORS["eig_cream_100"]],  # #FEECD6
    [1.0, BRAND_COLORS["eig_gold_600"]],   # #E1AD28
]

# Publication export size: 1950 x 1200 px == 6.5 x 4.0 in at 300 dpi.
EXPORT_WIDTH_PX = 1950
EXPORT_HEIGHT_PX = 1200

# DC is retained but too small to render on a state map; called out explicitly.
DC_LON, DC_LAT = -77.04, 38.90
DC_NOTE = "D.C. (too small to shade at this scale) has the highest average subsidy."


def build_choropleth(by_state: pd.DataFrame) -> go.Figure:
    """Build the Figure 1 choropleth from the by-state table."""
    fmt = ",.0f"

    fig = go.Figure(
        go.Choropleth(
            locations=by_state["state_code"],
            z=by_state["avg_annual_subsidy"],
            locationmode="USA-states",
            colorscale=COLOR_SCALE,
            colorbar=dict(
                title=dict(text=COLORBAR_TITLE, font=dict(size=12)),
                tickprefix="$",
                tickformat=fmt,
                thickness=16,
                len=0.65,
                x=0.92,
            ),
            marker_line_color="white",
            marker_line_width=0.5,
            hovertemplate=(
                "<b>%{location}</b><br>"
                f"Avg. annual subsidy: %{{z:{fmt}}}<extra></extra>"
            ),
        )
    )

    # Retain DC in the data (do not drop silently); add a readable callout marker.
    fig.add_trace(
        go.Scattergeo(
            lon=[DC_LON],
            lat=[DC_LAT],
            mode="markers+text",
            marker=dict(
                size=7,
                color=BRAND_COLORS["eig_gold_600"],
                line=dict(width=0.8, color=BRAND_COLORS["eig_black"]),
            ),
            text=["DC"],
            textposition="middle right",
            textfont=dict(family="Open Sans", size=11, color=BRAND_COLORS["eig_black"]),
            hoverinfo="skip",
            showlegend=False,
        )
    )

    fig.update_layout(
        **eig_plotly_layout(
            title_text=TITLE,
            geo=dict(
                scope="usa",
                showlakes=False,
                bgcolor="white",
                landcolor="#F5F5F5",
            ),
            # Room for the left-anchored title (top) and the note + source line (bottom).
            margin=dict(t=70, b=110, l=10, r=10),
        )
    )

    # DC visibility note, just above the source line.
    fig.add_annotation(
        text=DC_NOTE,
        xref="paper",
        yref="paper",
        x=0,
        y=-0.035,
        xanchor="left",
        yanchor="top",
        showarrow=False,
        font=dict(family="Open Sans", size=10, color="#777777"),
    )
    # Source line as the bottom-most annotation (EIG figure-style convention).
    fig.add_annotation(
        text=SOURCE_LINE,
        xref="paper",
        yref="paper",
        x=0,
        y=-0.085,
        xanchor="left",
        yanchor="top",
        showarrow=False,
        font=dict(family="Open Sans", size=11, color="#555555"),
    )
    return fig


def main() -> None:
    if not BY_STATE_PARQUET.exists():
        raise FileNotFoundError(
            f"Expected by-state data at {BY_STATE_PARQUET}. "
            "Run the population pipeline stage first."
        )

    by_state = pd.read_parquet(BY_STATE_PARQUET)
    required = {"state_code", "avg_annual_subsidy"}
    missing = required - set(by_state.columns)
    if missing:
        raise ValueError(f"by_state.parquet is missing columns: {sorted(missing)}")

    fig = build_choropleth(by_state)

    PATH_OUTPUT_FIG_MAIN.mkdir(parents=True, exist_ok=True)
    png_path = PATH_OUTPUT_FIG_MAIN / f"{FIG_STEM}.png"
    svg_path = PATH_OUTPUT_FIG_MAIN / f"{FIG_STEM}.svg"

    # scale=1 so pixel dimensions equal width/height (1950x1200 == 6.5x4.0in @ 300 dpi).
    fig.write_image(str(png_path), width=EXPORT_WIDTH_PX, height=EXPORT_HEIGHT_PX, scale=1)
    fig.write_image(str(svg_path), width=EXPORT_WIDTH_PX, height=EXPORT_HEIGHT_PX, scale=1)

    lo = by_state["avg_annual_subsidy"].min()
    hi = by_state["avg_annual_subsidy"].max()
    print(f"Rows: {len(by_state)} states (incl. DC). Value range: ${lo:,.0f}-${hi:,.0f}.")
    print(f"Wrote {png_path} ({png_path.stat().st_size:,} bytes)")
    print(f"Wrote {svg_path} ({svg_path.stat().st_size:,} bytes)")


if __name__ == "__main__":
    main()
